[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
TnBoardV1 = "DQPBAAvhsGhf9gp5wwa3tzvSUjS4wiUTDZnioFSkpugw"
TnCharSkillsV1 = "Bx1yYFTaYmjmvaQ3ep7iPqeutTjYSsZauzAQcUChvjQA"
TnCharStatusV1 = "5BBS4AUATNTRSyxrgmPRE3gnwYwkW1oZ22Er6aCFjWQz"
TnRankedPvpV1 = "4fqrH1Bi33PtjuGyFXwfvNKhnWG1yKLUU2SJUD95FY3P"
check_turn = "6D31googQLKy3edozYYLtws1m9Nnf9fdLzbAg2DpvWLR"
dq = "9FQ8ck9nj6z8Gs9q6iF75HySuF1KXyazKrQKb5kCYv2E"
itembox = "C7JFdGAV8HeTnv5zRFfKAXh2vCrUeuZWZeqekrX1RnAf"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"

[workspace]
members = ["programs/*", "programs-ecs/components/*", "programs-ecs/systems/*"]

[scripts]
create-collection = "yarn run ts-node --project ./tsconfig.json scripts/create-collection.ts"
init-itembox = "yarn run ts-node --project ./tsconfig.json scripts/init-itembox.ts"
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"

[test]
startup_wait = 5000
shutdown_wait = 2000
upgradeable = false

[[test.genesis]]
address = "WorLD15A7CrDwLcLy4fRqtaTb9fbd8o8iqiEMUDse2n"
program = "tests/fixtures/world.so"
upgradeable = false

[[test.genesis]]
address = "CoREENxT6tW1HoK8ypY1SxRMZTcVPm7R94rH4PZNhX7d"
program = "tests/fixtures/mpl_core.so"
upgradeable = false

[[test.genesis]]
address = "metaqbxxUerdq28cj1RbAWkYQm3ybzjb6a8bt518x1s"
program = "tests/fixtures/mpl_token_metadata.so"
upgradeable = false

[[test.genesis]]
address = "TokenzQdBNbLqP5VEhdkAS6EPFLC1PHnBqCXEpPxuEb"
program = "tests/fixtures/spl_token_2022.so"
upgradeable = false

[test.validator]
bind_address = "0.0.0.0"
url = "https://rpc.magicblock.app/devnet/"
ledger = ".bolt/test-ledger"
rpc_port = 8899

[[test.validator.account]]
address = "EHLkWwAT9oebVv9ht3mtqrvHhRVMKrt54tF3MfHTey2K"
filename = "tests/fixtures/registry.json"
