// pub mint: Pubkey,
//     pub energy: u8,
//     pub time_energy_gained: u64,
//     pub weapon_mint: Pubkey,
//     pub armor_mint: Pubkey,
//     pub generation: u8,
//     pub wins: u16,
//     pub loses: u16,